### ISSUE TITLE
periodic reconnect

### ISSUE THREAD

**Issue by willscott** [ipni/cassette#18]
> while reciprocal peering is better then non-reciprocal we still need (maybe you even have already) logic for reattempting connections to peering peers (I can link you to what is done in kubo, but it's nothing super special) since network hiccups or other issues could cause disconnections as well.

the kubo logic lives in https://github.com/ipfs/kubo/tree/master/peering

**Comment by willscott** [comment]
my reading of current logic is that once we register a peer from the peer store, we add them to our broadcast list, and will keep attempting to send them messages even if there is a disconnection, which should trigger a re-connection

**Comment by masih** [comment]
Cassette uses bitswap network to send messages and that implementation reconnects every time. 

Unless I've missed something I don't think we need reconnect mechanism.
